project:
  type: website
  render: 
    - "*.Rmd"
    - "*.rmd"
    - "*.qmd"
    - "!sesion*/"

website:
  title: "POL304 - Estadística para el Análisis Político 2"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de

      - text: Unidad_1
        menu: 
          - href: sesion1.qmd
            text: Modelo lineal

      - text: Unidad_2
        menu: 
          - href: sesion2.qmd
            text: De Poisson

          - href: sesion3.qmd
            text: Logística Binaria

      - text: Unidad_3
        menu: 
          - href: sesion4.qmd
            text: Clusters

          - href: sesion5.qmd
            text: Análisis Factorial

format:
  html:
    lang: es
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto # re-render only when source changes

